In [14]:
print(type(True))

<class 'bool'>


In [1]:
x=int(input())
y=int(input())
v=x*y
print(v)
i=x+y
print(i)
w=v/i
print(w)

 4
 6


24
10
2.4


In [2]:
n=8
if n%2==0:
    print("even")

    
else:
    print("odd")

even


In [3]:
a = 1
while a<=9:
    print(a)
    a+=1


1
2
3
4
5
6
7
8
9


In [6]:
a = int(input("num :"))
b=1
while b<=a:
    print(b)
    b+=1

num : 5


1
2
3
4
5


In [1]:
a = int(input("num :"))

while 0<=a:
    print(a)
    a=a-1

num : 4


4
3
2
1
0


In [3]:

a = int(input("1st num:"))
b = int(input("2nd num:"))
c = a+b
d = a*b

l = [a,b,c,d] 

for t in l:
    if t%2==0:
        print(t,"even")

    else:
        print(t,"odd")


1st num: 3
2nd num: 5


3 odd
5 odd
8 even
15 odd


In [3]:
a = int(input("1st num:"))
b = int(input("2nd num:"))
c = int(input("3rd num:"))

l = [a,b,c]
i = 0
j = len(l)

while i<j:
    if l[i]%2==0:
        print('even')
    else:
        print('odd')
    i=i+1    

1st num: 7
2nd num: 8
3rd num: 9


odd
even
odd


In [6]:
def itbd():
    print('tahasin')

itbd()
itbd()
    

tahasin
tahasin


In [15]:
a = 5+7
b = '6'
c = 5.99

print(int(b))

e=(str(a))

print(type(e))

print(int(c))

print(bool(a))



a = 5,6,8,9,0
print(str(a))
 



6
<class 'str'>
5
True
(5, 6, 8, 9, 0)


In [24]:
#comparison
a = 5>6
print(a)

b = 7>8
print(b)

c = 6==6
print(c)

d = 9!=8
print(d)

e = 5>=6
print(e)


False
False
True
True
False


In [36]:
#assignment

a=9
print(a)

k=6
l=9
k+=l
print(k)



w=8
o=6
w-=o
print(w)



c=9
e=7
c*=e
print(c)


v=8
p=6
v/=p
print(v)




9
15
2
63
1.3333333333333333


In [3]:
#logical

a= 8>4 and 5>0
print(a)

b = 5>7 or 9>8
print(b)

c = not 5>9
print(c)


True
True
True


In [5]:
#boolean

a = True
b = False
print(not b)






True


In [11]:
a = 'abcd'
b = 'bd'
print(b is not a)

True


In [13]:
a = 6 < 8

print(a)

True


In [1]:
#inner if

a =699
b=77
c=8

if a>b:       
    if b>c:
        print(b)
        
    else:
        print('noi')
    
else:
    print('c')


77


In [12]:
#ternary
a = 78
b = 8
o ='a' if a>b else 'b'
print(o)

a


In [2]:
num1 = 65
num2 = 76
print(num1 if num1>num2 else num2)


76


In [13]:
a = 76
b = 98
c = a>b and b>a
d = a>b or b>a
f = not c
print(c,d,f)

False True True


In [21]:
a = int(input())
if a>=80:
    print('a+')

elif a>=60:
    print('a-')
elif a>=50:
    print('b')
elif a>=33:
    print('c')

else:
    print('f')
      

    


 30


f


In [6]:
sum = 0
i = 1
while i <= 10:
    sum = sum+i
    i = i + 1
print(sum)
    

55


In [24]:
sum = 0
i = 1
while i <= 100:
    sum = sum+i
    break
    i = i+1
print(sum)
    

1


In [1]:
a = 0
while a<10:
    a += 1
    if a == 5:
        continue
 
    print(a)

1
2
3
4
6
7
8
9
10


In [11]:
a = 'tahasin'
b = 'a'
print(b in a)

True


In [1]:
a = ['tahasin','rakib','emon','shahed']
a.append('mustapiz')
print(a)

['tahasin', 'rakib', 'emon', 'shahed', 'mustapiz']


In [2]:
a = ['tahasin','rakib','emon','shahed']
a.append('mustapiz')
print(a)  

['tahasin', 'rakib', 'emon', 'shahed', 'mustapiz']


In [12]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [3]:
for i in range(10,0,-1):
    print(i)

10
9
8
7
6
5
4
3
2
1


In [24]:
age = int(input('age - '))
gender = input('gender-')

if age>=18 and gender=="male":
    print('adult male')
if age>=18 and gender=="female":
    print('adult female') 
else:
    print('no')


age -  77
gender- female


adult female


In [15]:
a = 5
b = 6

print(a!=b)  

True


In [16]:
a = [3,4,5,6,7,8,2,1]
a.insert(0,70)
print(a)

[70, 3, 4, 5, 6, 7, 8, 2, 1]


In [18]:
a = [3,4,5,6,7,8,2,1]
a.remove(3)
print(a)

[4, 5, 6, 7, 8, 2, 1]


In [29]:
a = [3,4,5,6,7,8,2,1]
a.clear()
print(a)

[]


In [27]:
a = [3,4,5,6,7,8,2,1]
a.remove()
print(a)

[3, 4, 5, 6, 7, 8, 2]


In [31]:
a = [3,4,5,6,7,8,2,1]

print(a[0])

3


In [33]:
lst = [1, 2, 3, 2, 4, 2]
print(lst[4])   
print(lst.count(2))  


4
3


In [34]:
a =int(input())

b = 0
c = 1
while c <= a:
    b = b+c
    c = c+1

print(b)    


 100


5050


In [5]:
a = 9
b = 8
print(a==b)

False


In [10]:
if 25>3:
    print('m')
elif 5==5:
    print('same')
    
else:
    print('no')

m


In [18]:


age = 20
a = "male"

if age > 18:
    if a == "male":
        print("Adult Male")




Adult Male


In [23]:
x = 'a' if 7>5 else "b"
print(x)

a


In [26]:
a = 5>4 and 4>3
b = 5>3 or 4>2
n = not 6>4
print(a,b,n)

True True False


In [40]:

for n in range(1,10,1):
    if n == 5:
        break
    print(n)

1
2
3
4


In [42]:

for n in range(1,11,1):
    if n == 5:
        continue
    print(n)

1
2
3
4
6
7
8
9
10


In [43]:
l = [8,7,5,6,3,2]
l.append(9)
print(l)


[8, 7, 5, 6, 3, 2, 9]


In [48]:
l = [8,7,5,6,3,2]
l.insert(5,3)
print(l)


[8, 7, 5, 6, 3, 3, 2]


In [51]:
l = [8,7,5,6,3,2]
l.remove(7)
print(l)


[8, 5, 6, 3, 2]


In [54]:
l = [8,7,5,6,3,2]
l.pop(0)
print(l)


[7, 5, 6, 3, 2]


In [55]:
l = [8,7,5,6,3,2]
l.clear()
print(l)


[]


In [1]:
l = [8,7,5,6,3,2,2,2,2]

print(l.count(2))


4


In [64]:
l = [8,7,5,6,3,2]
o = l.index(6)
print(o)


3


In [7]:

list = [ True,False]
print(list)

[True, False]


In [11]:
a = type(8987)
b = type('tahasin')
c = type(9.0087)
d = type(True)

l = [a,b,c,d]

for i in l:
    print(i)



<class 'int'>
<class 'str'>
<class 'float'>
<class 'bool'>


In [12]:
l = ['tahasin',7,1.0,True]

for i in l:
    print(type(i))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>


In [20]:
l = ['tahasin',7,1.0,True]
i = 0
p = len(l)
while i<p:
    print(type(l[i]))
    i+=1

<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>


In [26]:

list = ['tahasin','parvej','rakib']
list[0] = 'ta'
print(list)

['ta', 'parvej', 'rakib']


In [2]:
list = ['tahasin','parvej','rakib']
list.insert(2,'ok')
print(list)


['tahasin', 'parvej', 'ok', 'rakib']


In [29]:
list = ['tahasin','parvej','rakib']
list.append('ok')
print(list)

['tahasin', 'parvej', 'rakib', 'ok']


In [4]:
l1 = [1,2,3,4]
l2 = [5,6,7,8]
l3 = (l1+l2)
print(l3)

[1, 2, 3, 4, 5, 6, 7, 8]


In [36]:
l1 = [1,2,3,4]
l2 = [5,6,7,8]
print(l1+l2)

[1, 2, 3, 4, 5, 6, 7, 8]


In [37]:
l1 = [1,2,3,4]
l2 = [5,6,7,8]
lr = l1+l2
print(lr)

[1, 2, 3, 4, 5, 6, 7, 8]


In [38]:
l1 = [1,2,3,4]
l2 = [5,6,7,8]
l1 += l2
print(l1)

[1, 2, 3, 4, 5, 6, 7, 8]


In [39]:
l1 = [1,2,3,4]
l2 = [5,6,7,8]
l1.extend(l2)
print(l1)

[1, 2, 3, 4, 5, 6, 7, 8]


In [3]:
t = (1,2,3,4,5)
print(t)

(1, 2, 3, 4, 5)


In [11]:
se = {1,2,3,4,5,6,7}
print(se)


{1, 2, 3, 4, 5, 6, 7}


In [18]:
a = int(input('num :'))
if a%3==0 and a%5==0:
    print('yes')

else:
    print('no')

num : 15


yes


In [16]:
b = int(input('num:'))
if b>0:
    print('positive')

elif b<0:
    print('negative')
else:
    print('zero')

2.0


In [ ]:
c = int(input('num:'))
if c%2==0:
    print('even')

else:
    print("odd")

In [ ]:
a = input()
l = ['a','e','i','o','u','A','E','I','O','U']
l2 = ['b','c','d','f','g','h','j','k','l','m','n','p','q','r','s','t','v','w','x','y','z','B','C','D','F','G','H','J','K','L','M','N','P','Q','R','S','T','V','W','X','Y','Z']
if a in l:
    print('vowel')
elif a in l2:
    print('consonant')
else:
    print('nothing')

    

In [ ]:
a = input()
l = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
l2 = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']
if a in l:
    print('Lowercase')
elif a in l2:
    print('Uppercase')
else:
    print('nothing')

    

In [ ]:

while True:
    a = input()
    if a=="q":
        
        print("stop")
        break
          
    print(a)


 a


a


In [1]:
a = int(input())
b = int(input())
c = int(input())

l = [a,b,c]
i = 0
o = len(l)
while i<o:
    if l[i]%2==0:
        print('even') 
    else:
        print("odd")
    i += 1    



 3
 4
 5


odd
even
odd


In [2]:
a = int(input())
b=0
c=1
while c<a:
    b=b+c
    c+=1

print(b)

 7


21


In [5]:
a = int(input())
b=0
c=2
while c<a:
    b=b+c
    c+=2

print(b)

 100


2450


In [ ]:
a = int(input())
b = 1
while b<:
    c=a*b
    b+=1
print(c)

 3


In [12]:
a = int(input())
b = 1
while b<=10:
    c=a*b
    print(a,"*",b ,"=",c)
    b = b+1
   


 10


10 * 1 = 10
10 * 2 = 20
10 * 3 = 30
10 * 4 = 40
10 * 5 = 50
10 * 6 = 60
10 * 7 = 70
10 * 8 = 80
10 * 9 = 90
10 * 10 = 100


In [15]:

for i in range(1,100):
    if i%3==0 and i%5!=0:
        print(i)
    
    

3
6
9
12
18
21
24
27
33
36
39
42
48
51
54
57
63
66
69
72
78
81
84
87
93
96
99


In [37]:
l = [13,34,19,28,46,73,49,1,31,4,7,91,58,52,82,70,43,88,55,97,16,22,25,79,85,40,64,94,67,37]

l3 = []
for i in l:
    if i >= 50:
        continue
   
    l3.append(i)
print(l3)



[13, 34, 19, 28, 46, 49, 1, 31, 4, 7, 43, 16, 22, 25, 40, 37]


In [62]:
l = [40,45,33,34,8,38,28,22,1,7,49,41,14,5,22,39,15,19,36,37,43,2,5,42,46,48,49,12,48,37,8,20,30,20,4,37,27,29,7,44,15,32,35,10,28,18,2,15,36,38]
l2 = []
for i in l:
    
    if i not in l2:
        l2.append(i)

print(l2)
        
    

       


[40, 45, 33, 34, 8, 38, 28, 22, 1, 7, 49, 41, 14, 5, 39, 15, 19, 36, 37, 43, 2, 42, 46, 48, 12, 20, 30, 4, 27, 29, 44, 32, 35, 10, 18]


In [72]:
a = int(input())
b=1
while b<=a:
    print('*'*a)
    b+=1
    
    



 5


*****
*****
*****
*****
*****


In [10]:
a = input()

def myname():
    print('hello',a)

myname()

    

 tahasin


hello tahasin


In [17]:


def myname(name):
    return 'I',name
    


n = input()
myname(n)



    

 iui


('I', 'iui')

In [22]:
def f(x):
    return 2*x
    
a = int(input())
r = f(a)
print(r)

 5


10


In [18]:
def add(a,b,c):
    return a+b+c


n = int(input())
f = int(input())  
g = int(input())

r = add(n,f,g)
print(r)



 5
 8
 9


22


In [56]:
def mul(a,b,c):
    return a*b*c
n = int(input())
f = int(input())  
g = int(input())

l = mul(n,f,g)
print(l)



 2
 3
 1


6


In [57]:
def mul(a,b,c):
    return a*b+c
n = int(input())
f = int(input())  
g = int(input())

l = mul(n,f,g)
print(l)



 2
 3
 4


9


In [60]:
def div(a,b,c):
    return a/b/c
n = int(input())
f = int(input())  
g = int(input())

l = div(n,f,g)
print(int(l))



 100
 10
 2


5


In [66]:
def eo(a):
   
    if a%2==0:
        return 'even'
        
    else:
        return "odd"
       
    

x = int(input())
r = eo(x)
print(r)



    

 4


even


In [71]:
def eo(a): 
    if a%2==0:
        return 'even'    
    else:
        return "odd"
       
    

x = int(input())
b = int(input())
c = int(input())
r = eo(x),eo(b),eo(c)

print(r)



    

 3
 4
 5


('odd', 'even', 'odd')


In [8]:
def eo(a): 
    if a%2==0:
        return 'even'    
    else:
        return "odd"
x = int(input())
b = int(input())

print('c =',eo(x))
print('d =',eo(b))
print('e =',eo(x+b))
print('f =',eo(x-b))
print('h =',eo(x*b))
print('i =',eo(x/b))

 77
 99


c = odd
d = odd
e = even
f = even
h = odd
i = odd


In [27]:
def ta(x):
    a = x*x
    return a

e = int(input())
ta(e)

 4


16

In [29]:
def ta(x):
    return x*x
e = int(input())
ta(e)

 2


4

In [25]:
def f(x):
    v = x*x
    print(v)
    if v%2==0:
        return 'even'    
    else:
        return "odd"       
a = int(input())
r = f(a)
print(r)

 6


36
even


In [57]:
def bignum(a,b,c):
    if a>b and a>c:
        return a
    elif b>c and b>a:
        return b
    else:
        return c

x = int(input("num 1 ="))
y = int(input("num 2 ="))
z = int(input("num 3 ="))
print(bignum(x,y,z),"big")

num 1 = 6
num 2 = 5
num 3 = 4


6 big


In [ ]:
def mininum(m,l,k):
    if m<l and m<l:
        return m
    elif l<k and l<m:
        return l
    else:
        return k

m = int(input("num 1 ="))
l = int(input("num 2 ="))
k = int(input("num 3 ="))
print("min number", mininum(m,l,k))

In [2]:
def factorial(x):
    f = 1
    while x>=1:
        f = f*x
        x = x-1
    return f

x = int(input())
print(factorial(x))

 7


5040


In [6]:
def factorial(x):
    f = 1
    for i in range(1,x+1):
        f = f*i
    return f

x = int(input())
print(factorial(x))

 5


120


In [5]:
def area(x,y):
    return x*y
a = int(input())
b = int(input())
print(area(a,b))

 3
 4


12


In [4]:
def vc(x):
    vowels = "aeiouAEIOU"
    r = 0   
    for i in x:
        if i in vowels:
            r += 1
    return r

a = input()
print(vc(a))

 bangladesh


3


In [11]:
def namta(x):
    b = 1
    while b<=10:
        c = x*b
        print(x,"*",b,"=",c) 
        
        b= b+1
        
a = int(input())
print(namta(a))

 7


7 * 1 = 7
7 * 2 = 14
7 * 3 = 21
7 * 4 = 28
7 * 5 = 35
7 * 6 = 42
7 * 7 = 49
7 * 8 = 56
7 * 9 = 63
7 * 10 = 70
None


In [16]:
def namta(x):
    b = 1
    while b<=10:
        c = x*b
         
       
        b= b+1
    return c
        
a = int(input())
print(namta(a))

 6


6


In [44]:
def sum(x):
    s=0
    for i in range(1,x+1):
        s = s+i      
    print(s) 

a = int(input())
sum(a)
        

 88


3916


In [43]:
def sum(x):
    s=0
    l=1
    while s<=x:
        s=l+s
        l=l+1
    return s

a = int(input())
sum(a)
         
        
        
       
        

 4


6

In [42]:
def sume(x):
    s=0
    for i in range(1,x+1):
        if i%2==0:
            
            s=s+i
            
    return s

a = int(input())
sume(a)
        

 34


306

In [43]:
def sen(x):
    y = x.split()
    print(y)
    return len(y)
a = input()
sen(a)

 rrff fggy btr


['rrff', 'fggy', 'btr']


3

In [45]:
def sen(x):
    y = list(x)
    print(y)
    return len(y)
a = input()
sen(a)

 i love bd


['i', ' ', 'l', 'o', 'v', 'e', ' ', 'b', 'd']


9

In [68]:
def numoe(x):
    y = list(x)
    even =0
    odd =0
    for i in y:
        i = int(i)
        if i%2==0:
            print(i,"is even")
            even = even+1 
            
        else:
            print(i,"is odd")
            odd = odd+1
    print("even","=",even)
    print("odd","=",odd)
a = input()
numoe(a)


 3456789


3 is odd
4 is even
5 is odd
6 is even
7 is odd
8 is even
9 is odd
even = 3
odd = 4


In [88]:
def bigword(x):
    y = x.split()
    print(y)
    l = len(y)
    for i in y[0]:
        print(i)
         
                                



                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
a = input()
bigword(a)

 ghj hj hj 


['ghj', 'hj', 'hj']
g
h
j


In [16]:
def bigword(x):
    y = x.split()
    f = max(y,key=len)
    return f 
a = input()
print(bigword(a))

 uyfygu


['uyfygu']
uyfygu


In [9]:
def bigw(x):
    l = x.split()
    b = ""
    for i in l:    
        if len(i) > len(b):
            b = i
    print("big- ",b)
         
 
a = input()
bigw(a)

 hj yui hui


big-  yui


In [62]:
def bw(x):
    l = x.split()

    n = ""
    for i in l:
        if len(i) > len(n):
            n = i
    return n
a = input()
bw(a)

 i love bd


'love'

In [60]:
def pc(x):
    if x<2:
        return "not prime"
    for i in range(2,x):
        if x%i==0:
            return "not prime"
    return "prime"
a = int(input())
pc(a)

 47


'prime'

In [18]:
import numpy as np

zerod = np.array(9)
oned = np.array([9,8,6,6])
twod = np.array([[9,7,6,4],[7,8,0,5]])
threed = np.array([[[9,7,6,4],[7,8,0,5]],[[9,7,6,4],[7,8,0,5]]])

print(zerod)
print(oned)
print(twod)
print(threed)

print(zerod.ndim)
print(oned.ndim)
print(twod.ndim)
print(threed.ndim)



9
[9 8 6 6]
[[9 7 6 4]
 [7 8 0 5]]
[[[9 7 6 4]
  [7 8 0 5]]

 [[9 7 6 4]
  [7 8 0 5]]]
0
1
2
3


In [19]:
import numpy as np

zerod = np.array(9)

oned = np.array([9,8,6,6])


print(oned[2])


9
[9 8 6 6]
[[9 7 6 4]
 [7 8 0 5]]
[[[9 7 6 4]
  [7 8 0 5]]

 [[9 7 6 4]
  [7 8 0 5]]]
0
1
2
3
6


In [23]:
import numpy as np


threed = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(threed[1,1,0])


10


In [28]:
import numpy as np

zerod = np.array(9)   
oned = np.array([9,8,6,6])
twod = np.array([[9,7,6,4],[7,8,0,5]])
threed = np.array([[[9,7,6,4],[7,8,0,5]],[[9,7,6,4],[7,8,0,5]]])

print(oned.shape)
print(twod.shape)
print(threed.shape)

(4,)
(2, 4)
(2, 2, 4)


In [32]:
import numpy as np

twod = np.array([9,7,7,8,0,5])
 
l = twod.reshape(2,3)

print(l)


[[9 7 7]
 [8 0 5]]


In [5]:
import pandas as pd
data = {
    "name" : ["Tahasin","rakib","parvez"],
    "Roll" : [680269,680286,690571],
    "city" : ["dhaka","comilla","candina"]
}

df = pd.DataFrame(data)
print(df)

      name    Roll     city
0  Tahasin  680269    dhaka
1    rakib  680286  comilla
2   parvez  690571  candina
